name: Mapping Upload

on:
  workflow_dispatch:

jobs:
  mapping-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Grant execute permission to Gradle
        run: chmod +x ./gradlew

      - name: Build Release APK
        run: ./gradlew assembleRelease

      - name: Verify generated files
        run: |
          ls -R app/build/outputs/
          ls -R app/build/outputs/mapping/

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: app/build/outputs/apk/release/app-release.apk

      - name: Upload Mapping artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-mapping
          path: app/build/outputs/mapping/release/mapping.txt

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Upload APK to Firebase App Distribution
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          firebase appdistribution:distribute \
          app/build/outputs/apk/release/app-release.apk \
          --app ${{ secrets.FIREBASE_APP_ID }} \
          --groups "testers"

      - name: Upload mapping file to Crashlytics
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          firebase crashlytics:symbols:upload \
          --app=${{ secrets.FIREBASE_APP_ID }} \
          app/build/outputs/mapping/release/mapping.txt